### ISSUE TITLE
https://github.com/ELIXIR-UK-DaSH/FAIR-DaSH/issues/12

### ISSUE THREAD

**Issue by kkamieniecka** [elixir-uk/fellowship#1]
- **typos in REDCap and Sequencing data RDMbites tiles**
https://fellowship.elixiruknode.org/rdmbites
in both specialised is spelt incorrectly
- https://github.com/ELIXIR-UK-DaSH/FAIR-DaSH/issues/12
- **typo in 'course materials' tile on the home page**
 Within the 'Course materials' tile at the base of the homepage, workforce is spelt incorrectly
- **typos in cBioPortal within Course Materials**
https://fellowship.elixiruknode.org/course_materials
Introduction is spelt incorrectly in the title, and in the description it should be a tool not an tool
@egdelva

**Comment by egdelva** [comment]
@kkamieniecka 
the typo in 'Course Materials' tile on the homepage is still there, **workforce** is incorrect

the typo in the cBioPortal - 'introduction' is still spelt incorrectly within the mini menu on that page but is now correct everywhere else
the description for the Introduction to cBioPortal: should be 'a tool' - should've gone from 'an tool' to 'a tool' not just 'tool'
