### ISSUE TITLE
please check text of https://fellowship.elixiruknode.org/training_materials/

### ISSUE THREAD

**Issue by poterlowicz-lab** [elixir-uk/fellowship#20]
Please check the text for consistency, as it states that the course "can be taught face-to-face as part of The Carpentries." However, the course websites state, "This lesson is part of The Carpentries Incubator, a place to share and use each other's Carpentries-style lessons. This lesson has not been reviewed by, and is not endorsed by, The Carpentries."

**Comment by sitjart** [comment]
Do I understand that this also applies to our courses? 
Should we rename them as Carpentries style as opposed to Carpentries course?

**Comment by sitjart** [comment]
The consistency on entry titles has been resolved.,
