### ISSUE TITLE
Adding social media to mentor information

### ISSUE THREAD

**Issue by allysonlister** [elixir-uk/fellowship#7]
**Link to the page of interest**
https://fellowship.elixiruknode.org/mentors

**Describe what you would change to the page**
Here are some additional relevant social media accounts, please add as appropriate:

orcid: https://orcid.org/0000-0002-7702-4495
twitter: https://twitter.com/allysonlister
mastodon: https://fediscience.org/@allysonlister
linkedin: https://www.linkedin.com/in/allysonlister/

Thanks!

**Comment by nsjuty** [comment]
https://orcid.org/0000-0002-2036-8350

**Comment by RJMW** [comment]
https://orcid.org/0000-0002-8796-4771

**Comment by nomadscientist** [comment]
Wendi Bacon
orcid: https://orcid.org/0000-0002-8170-8806
LinkedIn: https://www.linkedin.com/in/wendi-bacon-7462aa100/
